### ISSUE TITLE
No reaction from menu

### ISSUE THREAD

**Issue by AndreasHoffmann2** [JetBrains/rider-efcore#164] opened 2023-05-03 06:38 UTC
#### Describe the bug

Not a single command in the submenu "Tools -> Entity Framework Core" does anything.

**To Reproduce**

Click on any item (e.g. "Scaffold DbContext")

#### Expected behavior

Some dialog should open.

### Environment (please complete the following information):

- OS: Windows 11
- .NET SDK info (installed ones and version used within Rider): .net 7.0
- Plugin version: current
- Rider version: 2023.1.1

#### Additional context

Rider displays that there was an internal error and shows the following stack-trace. Seems like displaying an error-message failed. I guess, I will be able to fix the underlying issue after finding the method-call "notifyEfIsNotInstalled" in the stack.

But you do probably want to fix the issue that no message is displayed.

java.lang.NullPointerException: Cannot invoke "com.intellij.notification.NotificationGroup.createNotification(String, com.intellij.notification.NotificationType)" because the return value of "com.intellij.notification.NotificationGroupManager.getNotificationGroup(String)" is null
	at me.seclerp.rider.plugins.efcore.features.shared.BaseCommandAction.notifyEfIsNotInstalled(BaseCommandAction.kt:93)
	at me.seclerp.rider.plugins.efcore.features.shared.BaseCommandAction.access$notifyEfIsNotInstalled(BaseCommandAction.kt:28)
	at me.seclerp.rider.plugins.efcore.features.shared.BaseCommandAction$actionPerformed$1.run(BaseCommandAction.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.codeWithMe.ClientId$Companion.decorateFunction$lambda$10(ClientId.kt:329)
	at com.intellij.codeWithMe.ClientId$Companion.decorateFunction$lambda$10(ClientId.kt:329)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by gananallenmckenzie** [comment] 2023-05-03 10:15
I am experiencing the same issue with the same environment setup and internal error report.

**Comment by seclerp** [comment] 2023-05-03 11:50
This is the duplicate of https://github.com/seclerp/rider-efcore/issues/162 and https://github.com/seclerp/rider-efcore/issues/163

It's already fixed in the branch but not released yet

**Closed as completed** 2023-05-11 21:08 UTC
Labels: bug
