### ISSUE TITLE
Unable to update database - wrong directory reference

### ISSUE THREAD

**Issue by pawelel** [JetBrains/rider-efcore#177] opened 2023-08-01 12:54 UTC
#### Describe the bug

Update-Database is not possible due to wrong working directory.

**To Reproduce**

Have project with multiple solutions.
Open aspnet-core directory.
Here is your working solution and src directory with project folders.
To update database, in command line open aspnet-core\src\MyProject.EntityFrameworkCore project directory and type 'dotnet ef database update'.
Even if this directory is open in the terminal, rider-efcore GUI doesn't respect it and picks root, which causes:
```bash
"C:\Program Files\dotnet\dotnet.exe" ef database update --project src\MyProject.EntityFrameworkCore\MyProject.EntityFrameworkCore.csproj --startup-project src\MyProject.Web.Host\MyProject.Web.Host.csproj --context MyProject.EntityFrameworkCore.MyProjectDbContext --configuration Debug 20230731181111_AddSomeEntities
Specify which project file to use because this 'D:\MyProjects\MyProject1\src\server\aspnet-core' contains more than one project file.
Process terminated with exit code 1
```

#### Expected behavior

Allow to select working directory or set Migrations project as working directory (can full path for projects solve this issue?)

#### Screenshots

![image](https://github.com/JetBrains/rider-efcore/assets/14290787/bf70d25d-b381-4127-9f61-bfbb8fad2bee)
![image](https://github.com/JetBrains/rider-efcore/assets/14290787/edede196-7529-430b-a85f-58de7d08ee1d)

### Environment (please complete the following information):

- OS: Win 11 x64 build 23511
- .NET SDK info (installed ones and version used within Rider): 7.0.306
- Plugin version: 232.0.0-rc1
- Rider version: 2023.2 RC

#### Additional context

stable version has the same issues.

**Comment by seclerp** [comment] 2023-08-01 19:45
Hi @pawelel, thanks for the issue! Do you have a minimal repro of the issue? It's not clear to me why EF Core fails to execute the command line, because both Migrations and Startup projects paths seems valid and they are relative to the solution directory (which is considered as `/aspnet-core`)

**Comment by seclerp** [comment] 2023-08-01 19:46
Do you have your projects in a completely different folder than the `.sln` file?

**Comment by pawelel** [comment] 2023-08-01 20:19
Hmm, I think similar situation can be found here: https://aspnetboilerplate.com/Templates https://github.com/aspnetboilerplate/aspnetboilerplate

**Comment by pawelel** [comment] 2023-08-01 20:57
@seclerp removing .dcproj files allowed me to update. Is it possible to ignore those files somehow?

**Comment by seclerp** [comment] 2023-08-02 17:16
Unfortunately, not really. There is [an issue](https://github.com/dotnet/efcore/issues/21655) on `dotnet ef` side, not sure if we can address it. 

We can't change the working directory for the command because then it will not work with the locally installed `dotnet ef`. I suggest you describe your case at the issue above.

From our side, I'll try to find some workarounds, as a temporary solution.

**Comment by pawelel** [comment] 2023-08-02 20:51
Thanks, luckily now we know the reason why migration doesn't work. The solution may be to temporarily move the *proj, .sln files from the working directory

**Comment by seclerp** [comment] 2023-08-03 14:11
Thanks for the investigation!

However, I still have no clue how to reproduce the issue with provided template:
```bash
> dotnet ef migrations add --project src/EFCoreIssue.EntityFrameworkCore/EFCoreIssue.EntityFrameworkCore.csproj --startup-project src/EFCoreIssue.Web.Host/EFCoreIssue.Web.Host.csproj --context EFCoreIssue.EntityFrameworkCore.EFCoreIssueDbContext --configuration Debug blablablablablabla
Build started...
Build succeeded.
The Entity Framework tools version '7.0.1' is older than that of the runtime '7.0.3'. Update the tools for the latest features and bug fixes. See https://aka.ms/AAc1fbw for more information.
Done. To undo this action, use 'ef migrations remove`
```

The same with `database update`. Maybe you can provide some step-by-step guide to reproduce? It will be very helpful and will provide the necessary info to look into possible workarounds.

**Comment by seclerp** [comment] 2023-08-03 14:35
Yeah, now it's reproducing. Unfortunately, the only option right now is to tweak with the `.dcproj` files location.

Closing this for now.

P.S. It's funny that the issue will not be reproduced when you have only 1 `.*proj` file near `.sln`, only more than one ([source](https://github.com/dotnet/sdk/blob/799cbc2fd4204db23ed49427dbabe1b1450fd7f2/src/Cli/dotnet/CommandFactory/CommandResolution/ProjectFactory.cs#L78)). Why it's treated like a project directory - I think because of local tools infrastructure, so fix may not be so trivial.

**Closed by seclerp** 2023-08-03 14:35 UTC
Labels: bug
