### ISSUE TITLE
[Bug] .NET 9 Target Framework Missing

### ISSUE THREAD

**Issue by Bram1903** [JetBrains/rider-efcore#245] opened 2024-10-11 18:00 UTC
#### Describe the bug

I am working on multiple projects, and today I updated one of them to .NET 9, following the release of .NET 9 Release Candidate 2. However, when trying to add a migration in the project targeting .NET 9, the target frameworks don't show up in the plugin. Initially, I suspected an installation issue, but after switching between projects using .NET 8 and .NET 9, it became evident that the issue only occurs with the .NET 9 plugin. I also tried removing both .NET 8 and .NET 9 to test the behavior, but the problem persisted. The same project works fine under .NET 8, but simply switching to the .NET 9 SDK renders the plugin unusable. Rider also displays a warning in the "Add migration" window when the project is set up to target .NET 9, as shown below:

![image](https://github.com/user-attachments/assets/5cc186ca-57e2-4b5a-9c19-a31635e4b462)
![image](https://github.com/user-attachments/assets/b97de1ec-6a58-4914-b07f-ce2ee67766f3)

#### To Reproduce

1. Open a project targeting .NET 9
2. Go to the "Add migration" window
3. Observe that it cannot find a target framework or any of the startup projects

#### Expected behavior

.NET 9 should appear as a valid target framework, and the startup project list should be populated.

#### Screenshots

.NET 8 (Working as expected):
![image](https://github.com/user-attachments/assets/500b6a63-fc61-432c-b52a-f06ca151fce3)

.NET 9:
![image](https://github.com/user-attachments/assets/5ced6f51-82d3-4f03-9599-49932b4e25c0)

### Environment:

- OS: Windows 11 (64-bit)
- .NET SDK info: .NET 8 & .NET 9 installed, using .NET 9 within Rider
- Plugin version: 1.5.25.10
- Rider version: 2024.2.6
- Microsoft.EntityFrameworkCore Library: 9.0.0-rc.1.24451.1 due to Npgsql.EntityFrameworkCore.PostgreSQL. not being updated yet.

**Comment by seclerp** [comment] 2024-10-11 18:09
Hi @Bram1903, thank you for reporting! The problem is known and will be fixed in one of the upcoming 2024.3 EAP versions of Rider.

**Comment by seclerp** [comment] 2024-10-24 19:24
Hi @Bram1903, the support for .NET 9 projects Is merged and will become available in 2024.3 EAP5.

**Closed by seclerp** 2024-10-24 19:24 UTC
Labels: bug

**Comment by Bram1903** [comment] 2024-10-24 19:25
Great to hear. Thanks for letting me know!
